export const users = [
  {
    id:1,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"1234567988",
    gender:"male",
    age:19,
    role:"doctor"
  },
  {
    id:2,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"15698753624",
    gender:"male",
    age:19,
    role:"doctor"
  },
  {
    id:3,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"1598753624",
    gender:"female",
    age:19,
    role:"doctor"
  },
  {
    id:4,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"4659781321",
    gender:"male",
    age:19,
    role:"patient"
  }
]
