export const patients = [
  {
    id:19,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"00000000000",
    gender:"Male",
    age:19,
    role:"doctor"
  },
  {
    id:19,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"00000000000",
    gender:"Male",
    age:19,
    role:"doctor"
  },
  {
    id:19,
    email:"email@email.com",
    name:"Name",
    phoneNumber:"00000000000",
    gender:"Male",
    age:19,
    role:"doctor"
  }
]
